from pydantic import BaseModel, Field
from typing import List, Optional

class AnalyzeTextRequest(BaseModel):
    """
    Schema for requesting real-time text analysis.
    """
    text: str = Field(..., description="The financial text or news headline to analyze", example="Tech giant XYZ reports record Q3 earnings, beating analyst expectations by 15%.")
    source: Optional[str] = Field("API", description="Optional source of the text")

class RiskSignalResponse(BaseModel):
    """
    Schema for the core risk signal output generated by the AI Engine.
    """
    id: Optional[int] = Field(None, description="Unique identifier for the processed signal")
    text: str = Field(..., description="The original text analyzed")
    sentiment_label: str = Field(..., description="Categorical sentiment: positive, negative, or neutral")
    sentiment_score: float = Field(..., description="Continuous sentiment score from -1.0 to 1.0")
    sentiment_confidence: float = Field(..., description="Model confidence for the sentiment prediction")
    event_class: str = Field(..., description="Zero-shot classification of the event type")
    event_confidence: float = Field(..., description="Model confidence for the event classification")
    impact_score: int = Field(..., description="Calculated severity/impact score from 1 to 10")

class SignalListResponse(BaseModel):
    """
    Schema for returning a list of pre-calculated risk signals.
    """
    status: str
    count: int
    data: List[RiskSignalResponse]
